services:
  n8n:
    container_name: n8n
    build:
      context: .docker
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 5678:5678
    environment:
      - GENERIC_TIMEZONE=Asia/Tokyo
      - TZ=Asia/Tokyo
    volumes:
      - n8n_data:/home/node/.n8n
      - ./.docker/claude/.claude.json:/home/node/.claude.json
      - ./.docker/claude/.claude.json:/home/node/.claude.json.backup
      - ./.docker/claude/.claude:/home/node/.claude
  mailpit:
    container_name: mailpit
    image: axllent/mailpit
    restart: unless-stopped
    ports:
      - 8025:8025
      - 1025:1025
volumes:
  n8n_data: